const channels = [
    {
        name: "3 Tamil TV (720p) [Not 24/7]",
        tvg: {
            id: "3TamilTV.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "https://i.imgur.com/WfAU7pB.png",
            url: "",
            rec: "",
        },
        group: { title: "Entertainment" },
        http: { referrer: "", "user-agent": "" },
        url: "https://6n3yogbnd9ok-hls-live.5centscdn.com/threetamil/d0dbe915091d400bd8ee7f27f0791303.sdp/index.m3u8",
        raw: '#EXTINF:-1 tvg-id="3TamilTV.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="https://i.imgur.com/WfAU7pB.png" group-title="Entertainment",3 Tamil TV (720p) [Not 24/7]\nhttps://6n3yogbnd9ok-hls-live.5centscdn.com/threetamil/d0dbe915091d400bd8ee7f27f0791303.sdp/index.m3u8',
        line: 2,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "7S Music (576p) [Not 24/7]",
        tvg: {
            id: "7SMusic.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "https://i.imgur.com/P5EXpPy.jpg",
            url: "",
            rec: "",
        },
        group: { title: "Music" },
        http: { referrer: "", "user-agent": "" },
        url: "http://103.199.161.254/Content/7smusic/Live/Channel(7smusic)/index.m3u8",
        raw: '#EXTINF:-1 tvg-id="7SMusic.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="https://i.imgur.com/P5EXpPy.jpg" group-title="Music",7S Music (576p) [Not 24/7]\nhttp://103.199.161.254/Content/7smusic/Live/Channel(7smusic)/index.m3u8',
        line: 4,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "Akaram Kidz (460p) [Not 24/7]",
        tvg: {
            id: "AkaramKidz.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "https://i.imgur.com/hAgaVPa.jpg",
            url: "",
            rec: "",
        },
        group: { title: "Kids" },
        http: { referrer: "", "user-agent": "" },
        url: "http://akaram.zecast.net/akaram-live/akaramkidz/index.m3u8",
        raw: '#EXTINF:-1 tvg-id="AkaramKidz.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="https://i.imgur.com/hAgaVPa.jpg" group-title="Kids",Akaram Kidz (460p) [Not 24/7]\nhttp://akaram.zecast.net/akaram-live/akaramkidz/index.m3u8',
        line: 6,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "Asianet News Tamil (360p) [Not 24/7]",
        tvg: {
            id: "AsianetNewsTamil.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "https://static.asianetnews.com/v1/images/tamil_logo.png",
            url: "",
            rec: "",
        },
        group: { title: "News" },
        http: { referrer: "", "user-agent": "" },
        url: "https://vidcdn.vidgyor.com/ptm-origin/aslive/playlist.m3u8",
        raw: '#EXTINF:-1 tvg-id="AsianetNewsTamil.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="https://static.asianetnews.com/v1/images/tamil_logo.png" group-title="News",Asianet News Tamil (360p) [Not 24/7]\nhttps://vidcdn.vidgyor.com/ptm-origin/aslive/playlist.m3u8',
        line: 8,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "Astro Vaanavil [Geo-blocked]",
        tvg: {
            id: "AstroVaanavil.my",
            name: "",
            language: "Tamil",
            country: "MY",
            logo: "https://divign0fdw3sv.cloudfront.net/Images/ChannelLogo/contenthub/397_144.png",
            url: "",
            rec: "",
        },
        group: { title: "Undefined" },
        http: { referrer: "", "user-agent": "" },
        url: "https://agsplayback01.astro.com.my/CH3/master_VAANGOSHOP5.m3u8",
        raw: '#EXTINF:-1 tvg-id="AstroVaanavil.my" tvg-country="MY" tvg-language="Tamil" tvg-logo="https://divign0fdw3sv.cloudfront.net/Images/ChannelLogo/contenthub/397_144.png" group-title="Undefined",Astro Vaanavil [Geo-blocked]\nhttps://agsplayback01.astro.com.my/CH3/master_VAANGOSHOP5.m3u8',
        line: 10,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "Captain TV (576p) [Not 24/7]",
        tvg: {
            id: "CaptainTV.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "https://i.imgur.com/UXg6sac.png",
            url: "",
            rec: "",
        },
        group: { title: "Entertainment" },
        http: { referrer: "", "user-agent": "" },
        url: "http://103.199.160.85/Content/captain/Live/Channel(Captain)/index.m3u8",
        raw: '#EXTINF:-1 tvg-id="CaptainTV.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="https://i.imgur.com/UXg6sac.png" group-title="Entertainment",Captain TV (576p) [Not 24/7]\nhttp://103.199.160.85/Content/captain/Live/Channel(Captain)/index.m3u8',
        line: 12,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "EET TV (1080p) [Not 24/7]",
        tvg: {
            id: "EETTV.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "https://i.imgur.com/f7J37yv.png",
            url: "",
            rec: "",
        },
        group: { title: "Entertainment" },
        http: { referrer: "", "user-agent": "" },
        url: "https://live.streamjo.com/eetlive/eettv.m3u8",
        raw: '#EXTINF:-1 tvg-id="EETTV.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="https://i.imgur.com/f7J37yv.png" group-title="Entertainment",EET TV (1080p) [Not 24/7]\nhttps://live.streamjo.com/eetlive/eettv.m3u8',
        line: 14,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "Imayam (480p) [Not 24/7]",
        tvg: {
            id: "Imayam.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "https://i.imgur.com/CzdM0pg.png",
            url: "",
            rec: "",
        },
        group: { title: "Entertainment" },
        http: { referrer: "", "user-agent": "" },
        url: "https://idvd.multitvsolution.com/idvo/imayamtv.m3u8",
        raw: '#EXTINF:-1 tvg-id="Imayam.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="https://i.imgur.com/CzdM0pg.png" group-title="Entertainment",Imayam (480p) [Not 24/7]\nhttps://idvd.multitvsolution.com/idvo/imayamtv.m3u8',
        line: 16,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "Isai Aruvi (576p)",
        tvg: {
            id: "IsaiAruvi.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "https://i.imgur.com/radWIeb.png",
            url: "",
            rec: "",
        },
        group: { title: "Music" },
        http: { referrer: "", "user-agent": "" },
        url: "http://103.199.161.254/Content/isaiaruvi/Live/Channel(IsaiAruvi)/index.m3u8",
        raw: '#EXTINF:-1 tvg-id="IsaiAruvi.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="https://i.imgur.com/radWIeb.png" group-title="Music",Isai Aruvi (576p)\nhttp://103.199.161.254/Content/isaiaruvi/Live/Channel(IsaiAruvi)/index.m3u8',
        line: 18,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "Kalai Isai (1080p) [Not 24/7]",
        tvg: {
            id: "KalaiIsai.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "",
            url: "",
            rec: "",
        },
        group: { title: "Music" },
        http: { referrer: "", "user-agent": "" },
        url: "http://singamcloud.in:1935/kalai/kalaiisai/playlist.m3u8",
        raw: '#EXTINF:-1 tvg-id="KalaiIsai.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="" group-title="Music",Kalai Isai (1080p) [Not 24/7]\nhttp://singamcloud.in:1935/kalai/kalaiisai/playlist.m3u8',
        line: 20,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "Kalaignar (576p)",
        tvg: {
            id: "Kalaignar.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "https://upload.wikimedia.org/wikipedia/en/3/3a/Kalaignar_logo.jpg",
            url: "",
            rec: "",
        },
        group: { title: "Undefined" },
        http: { referrer: "", "user-agent": "" },
        url: "http://103.199.161.254/Content/kalaignartv/Live/Channel(KalaignarTV)/index.m3u8",
        raw: '#EXTINF:-1 tvg-id="Kalaignar.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="https://upload.wikimedia.org/wikipedia/en/3/3a/Kalaignar_logo.jpg" group-title="Undefined",Kalaignar (576p)\nhttp://103.199.161.254/Content/kalaignartv/Live/Channel(KalaignarTV)/index.m3u8',
        line: 22,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "Kalaignar Murasu (576p) [Not 24/7]",
        tvg: {
            id: "KalaignarMurasu.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "https://i.imgur.com/ZDXVWVQ.png",
            url: "",
            rec: "",
        },
        group: { title: "Music" },
        http: { referrer: "", "user-agent": "" },
        url: "http://103.199.160.85/Content/kalaignarmurasu/Live/Channel(KalaignarMurasu)/index.m3u8",
        raw: '#EXTINF:-1 tvg-id="KalaignarMurasu.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="https://i.imgur.com/ZDXVWVQ.png" group-title="Music",Kalaignar Murasu (576p) [Not 24/7]\nhttp://103.199.160.85/Content/kalaignarmurasu/Live/Channel(KalaignarMurasu)/index.m3u8',
        line: 24,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "Kalaignar Seithikal (576p) [Not 24/7]",
        tvg: {
            id: "KalaignarSeithikal.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "https://i.imgur.com/qWOnWhQ.png",
            url: "",
            rec: "",
        },
        group: { title: "News" },
        http: { referrer: "", "user-agent": "" },
        url: "http://103.199.160.85/Content/kalaignarseithikal/Live/Channel(KalaignarSeithikal)/index.m3u8",
        raw: '#EXTINF:-1 tvg-id="KalaignarSeithikal.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="https://i.imgur.com/qWOnWhQ.png" group-title="News",Kalaignar Seithikal (576p) [Not 24/7]\nhttp://103.199.160.85/Content/kalaignarseithikal/Live/Channel(KalaignarSeithikal)/index.m3u8',
        line: 26,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "Kalaignar Sirippoli (576p)",
        tvg: {
            id: "KalaignarSirippoli.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "https://i.imgur.com/bqXRXaZ.png",
            url: "",
            rec: "",
        },
        group: { title: "Comedy" },
        http: { referrer: "", "user-agent": "" },
        url: "http://103.199.161.254/Content/kalaignarsirippoli/Live/Channel(Kalaignarsirippoli)/index.m3u8",
        raw: '#EXTINF:-1 tvg-id="KalaignarSirippoli.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="https://i.imgur.com/bqXRXaZ.png" group-title="Comedy",Kalaignar Sirippoli (576p)\nhttp://103.199.161.254/Content/kalaignarsirippoli/Live/Channel(Kalaignarsirippoli)/index.m3u8',
        line: 28,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "Makkal TV (576p) [Not 24/7]",
        tvg: {
            id: "MakkalTV.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "https://i.imgur.com/Sv4bLGX.png",
            url: "",
            rec: "",
        },
        group: { title: "General" },
        http: { referrer: "", "user-agent": "" },
        url: "http://14.199.164.20:4001/play/a0l1/index.m3u8",
        raw: '#EXTINF:-1 tvg-id="MakkalTV.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="https://i.imgur.com/Sv4bLGX.png" group-title="General",Makkal TV (576p) [Not 24/7]\nhttp://14.199.164.20:4001/play/a0l1/index.m3u8',
        line: 30,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "Marutam TV (720p) [Not 24/7]",
        tvg: {
            id: "MarutamTV.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "https://i.imgur.com/cFNw4Af.png",
            url: "",
            rec: "",
        },
        group: { title: "Entertainment" },
        http: { referrer: "", "user-agent": "" },
        url: "http://mntv.livebox.co.in/mntvhls/mntv.m3u8",
        raw: '#EXTINF:-1 tvg-id="MarutamTV.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="https://i.imgur.com/cFNw4Af.png" group-title="Entertainment",Marutam TV (720p) [Not 24/7]\nhttp://mntv.livebox.co.in/mntvhls/mntv.m3u8',
        line: 32,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "MK Six (576p) [Not 24/7]",
        tvg: {
            id: "MKSix.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "https://i.imgur.com/FAytBoW.png",
            url: "",
            rec: "",
        },
        group: { title: "Undefined" },
        http: { referrer: "", "user-agent": "" },
        url: "http://103.199.160.85/Content/mktv6/Live/Channel(MKTV6)/index.m3u8",
        raw: '#EXTINF:-1 tvg-id="MKSix.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="https://i.imgur.com/FAytBoW.png" group-title="Undefined",MK Six (576p) [Not 24/7]\nhttp://103.199.160.85/Content/mktv6/Live/Channel(MKTV6)/index.m3u8',
        line: 34,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "MK Tunes (576p) [Not 24/7]",
        tvg: {
            id: "MKTunes.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "https://i.imgur.com/m8DPQd6.png",
            url: "",
            rec: "",
        },
        group: { title: "Undefined" },
        http: { referrer: "", "user-agent": "" },
        url: "http://103.199.160.85/Content/mktunes/Live/Channel(MKTunes)/index.m3u8",
        raw: '#EXTINF:-1 tvg-id="MKTunes.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="https://i.imgur.com/m8DPQd6.png" group-title="Undefined",MK Tunes (576p) [Not 24/7]\nhttp://103.199.160.85/Content/mktunes/Live/Channel(MKTunes)/index.m3u8',
        line: 36,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "MK TV (576p) [Not 24/7]",
        tvg: {
            id: "MKTV.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "https://i.imgur.com/UxxbaR3.png",
            url: "",
            rec: "",
        },
        group: { title: "Entertainment" },
        http: { referrer: "", "user-agent": "" },
        url: "http://103.199.160.85/Content/mktv/Live/Channel(MKTV)/index.m3u8",
        raw: '#EXTINF:-1 tvg-id="MKTV.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="https://i.imgur.com/UxxbaR3.png" group-title="Entertainment",MK TV (576p) [Not 24/7]\nhttp://103.199.160.85/Content/mktv/Live/Channel(MKTV)/index.m3u8',
        line: 38,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "News 7 Tamil (1080p) [Not 24/7]",
        tvg: {
            id: "News7Tamil.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "https://i.imgur.com/oBjgUTc.png",
            url: "",
            rec: "",
        },
        group: { title: "News" },
        http: { referrer: "", "user-agent": "" },
        url: "http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UC2f4w_ppqHplvjiNaoTAK9w/live",
        raw: '#EXTINF:-1 tvg-id="News7Tamil.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="https://i.imgur.com/oBjgUTc.png" group-title="News",News 7 Tamil (1080p) [Not 24/7]\nhttp://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UC2f4w_ppqHplvjiNaoTAK9w/live',
        line: 40,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "News 18 Tamil (360p)",
        tvg: {
            id: "News18Tamil.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "https://static.wikia.nocookie.net/logopedia/images/a/a8/News18_Tamilnadu.jpeg/revision/latest?cb=20191220041122",
            url: "",
            rec: "",
        },
        group: { title: "News" },
        http: { referrer: "", "user-agent": "" },
        url: "https://news18tamil-lh.akamaihd.net/i/n18tamil_1@526595/index_4_av-p.m3u8?rebase=on&sd=10",
        raw: '#EXTINF:-1 tvg-id="News18Tamil.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/a/a8/News18_Tamilnadu.jpeg/revision/latest?cb=20191220041122" group-title="News",News 18 Tamil (360p)\nhttps://news18tamil-lh.akamaihd.net/i/n18tamil_1@526595/index_4_av-p.m3u8?rebase=on&sd=10',
        line: 42,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "Polimer News (720p) [Geo-blocked]",
        tvg: {
            id: "PolimerNews.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "https://india.mom-rsf.org/typo3temp/_processed_/d/c/csm_16526-1592_import_d84315ad22.png",
            url: "",
            rec: "",
        },
        group: { title: "News" },
        http: { referrer: "", "user-agent": "" },
        url: "https://versewsa.pc.cdn.bitgravity.com/versewsa/live/polimernews.smil/chunklist_b1800000.m3u8",
        raw: '#EXTINF:-1 tvg-id="PolimerNews.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="https://india.mom-rsf.org/typo3temp/_processed_/d/c/csm_16526-1592_import_d84315ad22.png" group-title="News",Polimer News (720p) [Geo-blocked]\nhttps://versewsa.pc.cdn.bitgravity.com/versewsa/live/polimernews.smil/chunklist_b1800000.m3u8',
        line: 44,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "Puthuyugam TV (576p) [Not 24/7]",
        tvg: {
            id: "PuthuyugamTV.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "https://i.imgur.com/1q1LQQ9.png",
            url: "",
            rec: "",
        },
        group: { title: "Undefined" },
        http: { referrer: "", "user-agent": "" },
        url: "http://103.199.160.85/Content/puthuyugam/Live/Channel(Puthuyugam)/index.m3u8",
        raw: '#EXTINF:-1 tvg-id="PuthuyugamTV.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="https://i.imgur.com/1q1LQQ9.png" group-title="Undefined",Puthuyugam TV (576p) [Not 24/7]\nhttp://103.199.160.85/Content/puthuyugam/Live/Channel(Puthuyugam)/index.m3u8',
        line: 46,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "Sana Plus (720p) [Not 24/7]",
        tvg: {
            id: "SanaPlus.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "https://i.imgur.com/cA7PpJG.jpg",
            url: "",
            rec: "",
        },
        group: { title: "Music" },
        http: { referrer: "", "user-agent": "" },
        url: "http://media.7starcloud.com:1935/live/sanatv2/playlist.m3u8",
        raw: '#EXTINF:-1 tvg-id="SanaPlus.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="https://i.imgur.com/cA7PpJG.jpg" group-title="Music",Sana Plus (720p) [Not 24/7]\nhttp://media.7starcloud.com:1935/live/sanatv2/playlist.m3u8',
        line: 48,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "Sana TV (576p) [Not 24/7]",
        tvg: {
            id: "SanaTV.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "https://i.imgur.com/D03gyp2.png",
            url: "",
            rec: "",
        },
        group: { title: "Entertainment" },
        http: { referrer: "", "user-agent": "" },
        url: "http://hdserver.7starcloud.com:1935/sanatv/sanatv/playlist.m3u8",
        raw: '#EXTINF:-1 tvg-id="SanaTV.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="https://i.imgur.com/D03gyp2.png" group-title="Entertainment",Sana TV (576p) [Not 24/7]\nhttp://hdserver.7starcloud.com:1935/sanatv/sanatv/playlist.m3u8',
        line: 50,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "Santhora Short Flim (720p)",
        tvg: {
            id: "SanthoraShortFlim.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "https://i.imgur.com/kKFfLMd.jpg",
            url: "",
            rec: "",
        },
        group: { title: "Movies" },
        http: { referrer: "", "user-agent": "" },
        url: "http://rtmp.santhoratv.zecast.net/santhora/santhorashortfilm/playlist.m3u8",
        raw: '#EXTINF:-1 tvg-id="SanthoraShortFlim.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="https://i.imgur.com/kKFfLMd.jpg" group-title="Movies",Santhora Short Flim (720p)\nhttp://rtmp.santhoratv.zecast.net/santhora/santhorashortfilm/playlist.m3u8',
        line: 52,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "Santhora TV (720p)",
        tvg: {
            id: "SanthoraTV.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "https://i.imgur.com/LsacUVi.png",
            url: "",
            rec: "",
        },
        group: { title: "Undefined" },
        http: { referrer: "", "user-agent": "" },
        url: "http://santhoratv.zecast.net/santhoratv/santhoratv/index.m3u8",
        raw: '#EXTINF:-1 tvg-id="SanthoraTV.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="https://i.imgur.com/LsacUVi.png" group-title="Undefined",Santhora TV (720p)\nhttp://santhoratv.zecast.net/santhoratv/santhoratv/index.m3u8',
        line: 54,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "Tamil Vision TV (1080p)",
        tvg: {
            id: "TamilVisionTV.ca",
            name: "",
            language: "Tamil",
            country: "CA;IN",
            logo: "https://i.imgur.com/jSWRXdg.png",
            url: "",
            rec: "",
        },
        group: { title: "Undefined" },
        http: { referrer: "", "user-agent": "" },
        url: "http://live.tamilvision.tv:8081/TVI/HD/playlist.m3u8",
        raw: '#EXTINF:-1 tvg-id="TamilVisionTV.ca" tvg-country="CA;IN" tvg-language="Tamil" tvg-logo="https://i.imgur.com/jSWRXdg.png" group-title="Undefined",Tamil Vision TV (1080p)\nhttp://live.tamilvision.tv:8081/TVI/HD/playlist.m3u8',
        line: 56,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "Thanthi TV (720p) [Not 24/7]",
        tvg: {
            id: "ThanthiTV.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "https://images-eu.ssl-images-amazon.com/images/I/71QprgRT4rL.png",
            url: "",
            rec: "",
        },
        group: { title: "News" },
        http: { referrer: "", "user-agent": "" },
        url: "https://vidcdn.vidgyor.com/thanthi-origin/liveabr/playlist.m3u8",
        raw: '#EXTINF:-1 tvg-id="ThanthiTV.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="https://images-eu.ssl-images-amazon.com/images/I/71QprgRT4rL.png" group-title="News",Thanthi TV (720p) [Not 24/7]\nhttps://vidcdn.vidgyor.com/thanthi-origin/liveabr/playlist.m3u8',
        line: 58,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "Vaanvavil (576p) [Not 24/7]",
        tvg: {
            id: "Vaanavil.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "https://i.imgur.com/etr1k08.png",
            url: "",
            rec: "",
        },
        group: { title: "Music" },
        http: { referrer: "", "user-agent": "" },
        url: "http://14.199.164.20:4001/play/a0nx/index.m3u8",
        raw: '#EXTINF:-1 tvg-id="Vaanavil.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="https://i.imgur.com/etr1k08.png" group-title="Music",Vaanvavil (576p) [Not 24/7]\nhttp://14.199.164.20:4001/play/a0nx/index.m3u8',
        line: 60,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "Vasantham [Geo-blocked]",
        tvg: {
            id: "Vasantham.sg",
            name: "",
            language: "English;Tamil",
            country: "SG",
            logo: "",
            url: "",
            rec: "",
        },
        group: { title: "Undefined" },
        http: { referrer: "", "user-agent": "" },
        url: "https://d39v9xz8f7n8tk.cloudfront.net/hls/clr4ctv_vsnthm/master.m3u8",
        raw: '#EXTINF:-1 tvg-id="Vasantham.sg" tvg-country="SG" tvg-language="English;Tamil" tvg-logo="" group-title="Undefined",Vasantham [Geo-blocked]\nhttps://d39v9xz8f7n8tk.cloudfront.net/hls/clr4ctv_vsnthm/master.m3u8',
        line: 62,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "Vathanam TV [Timeout]",
        tvg: {
            id: "VathanamTV.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "",
            url: "",
            rec: "",
        },
        group: { title: "Undefined" },
        http: { referrer: "", "user-agent": "" },
        url: "http://95.216.167.183:5080/LiveApp/streams/443106610169904881506470.m3u8",
        raw: '#EXTINF:-1 tvg-id="VathanamTV.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="" group-title="Undefined",Vathanam TV [Timeout]\nhttp://95.216.167.183:5080/LiveApp/streams/443106610169904881506470.m3u8',
        line: 64,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "Velicham (360p) [Not 24/7]",
        tvg: {
            id: "Velicham.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "https://i.imgur.com/YeR3mm9.png",
            url: "",
            rec: "",
        },
        group: { title: "Entertainment" },
        http: { referrer: "", "user-agent": "" },
        url: "https://rtmp.smartstream.video/velichamtv/velichamtv/playlist.m3u8",
        raw: '#EXTINF:-1 tvg-id="Velicham.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="https://i.imgur.com/YeR3mm9.png" group-title="Entertainment",Velicham (360p) [Not 24/7]\nhttps://rtmp.smartstream.video/velichamtv/velichamtv/playlist.m3u8',
        line: 66,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
    {
        name: "Yupp Thirai (270p)",
        tvg: {
            id: "YuppThirai.in",
            name: "",
            language: "Tamil",
            country: "IN",
            logo: "https://i.imgur.com/6E8SbCf.png",
            url: "",
            rec: "",
        },
        group: { title: "Movies" },
        http: { referrer: "", "user-agent": "" },
        url: "http://119.81.82.28/encoded/yuppthirai_800/playlist.m3u8",
        raw: '#EXTINF:-1 tvg-id="YuppThirai.in" tvg-country="IN" tvg-language="Tamil" tvg-logo="https://i.imgur.com/6E8SbCf.png" group-title="Movies",Yupp Thirai (270p)\nhttp://119.81.82.28/encoded/yuppthirai_800/playlist.m3u8',
        line: 68,
        catchup: { type: "", days: "", source: "" },
        timeshift: "",
    },
];

export default channels;
